.TH CHRONOSPLIT 1 "02-08-2026" "chronosplit" "User Commands"
.SH NAME
chronosplit \- Checkpoint-based time tracker.
.SH SYNOPSIS
.B chronosplit
.SH DESCRIPTION
.B chronosplit
is simple TUI application to track time in work blocks with checkpoints, custom project and subject tags. The data is stored in SQLite database.
.SH AUTHOR
Written by Karel Hanák <khgreav@gmail.com>.
.SH BUGS
Report bugs to <https://github.com/khgreav/chronosplit>.
