#!/bin/sh

set -e

LIB_DIR=/var/lib/chronoshift

case "$1" in
    configure)
        if [ ! -d "$LIB_DIR" ]; then
            mkdir -p "$LIB_DIR"
        fi
        chmod 0777 "$LIB_DIR"
        ;;
esac

#DEBHELPER#
